Konzole.InventorySystem.Web/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Konzole.InventorySystem;
using Konzole.InventorySystem.Providers.Interface;
using Konzole.InventorySystem.Web.Models;

namespace Konzole.InventorySystem.Web.Controllers
{
    public class CustomersController : Controller
    {
        private ICustomerProvider _customerProvider = null;

        public CustomersController(ICustomerProvider customerProvider)
        {
            this._customerProvider = customerProvider;
        }

        // GET: Customers
        public ActionResult Index()
        {
            return View(this._customerProvider.GetList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = this._customerProvider.GetByCustomerId(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //// GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Address,Contact,TIN")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                this._customerProvider.Save(customer);
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = _customerProvider.GetByCustomerId(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Address,Contact,TIN")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _customerProvider.Save(customer);
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = _customerProvider.GetByCustomerId(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _customerProvider.RemoveById(id);
            return RedirectToAction("Index");
        }
    }
}

Konzole.InventorySystem.Web/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Konzole.InventorySystem;
using Konzole.InventorySystem.Providers.Interface;
using Konzole.InventorySystem.Web.Models;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using Konzole.InventorySystem.Infrastructure;

namespace Konzole.InventorySystem.Web.Controllers
{
    public class SuppliersController : Controller
    {
        private ISupllierProvider _supplierProvider = null;


        public SuppliersController(ISupllierProvider supplierProvider)
        {
            this._supplierProvider = supplierProvider;
        }

        // GET: Suppliers
        public ActionResult Index()
        {
            return View(this._supplierProvider.GetList());
        }

        // GET: Suppliers/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = this._supplierProvider.GetBySupplierId(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // GET: Suppliers/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SupplierName,Address,Contact,Status")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                this._supplierProvider.Save(supplier);
                return RedirectToAction("Index");
            }

            return View(supplier);
        }

        // GET: Suppliers/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = _supplierProvider.GetBySupplierId(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SupplierName,Address,Contact,Status")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _supplierProvider.Save(supplier);
                return RedirectToAction("Index");
            }
            return View(supplier);
        }


        // GET: Suppliers/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = _supplierProvider.GetBySupplierId(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _supplierProvider.RemoveById(id);
            return RedirectToAction("Index");
        }

        [ActionName("SupplierNavigator")]
        public ActionResult fncGetResumeNavigation()
        {
            return PartialView();
        }


        [ActionName("SupplierScripts")]
        public PartialViewResult fncGetJavaScriptForResumeBuilder()
        {
            return PartialView();
        }



        //[Authorize]
        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Search")]
        public ActionResult GenerateGrid()
        {
            
            IEnumerable<Supplier> data = this._supplierProvider.GetList();
            return View(data);
        }

        //[Authorize]

        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Export")]
        public ActionResult ExportToExcel()
        {
            

            GridView gv = new GridView();

            var data = this._supplierProvider.GetList();
            gv.DataSource = data.Select(a => new Supplier
            {
                SupplierName = a.SupplierName,
                Address = a.Address,
                Contact = a.Contact,
                Email = a.Email
            });

            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=Supplier.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            gv.RenderControl(htw);
            Response.Output.Write(sw.ToString());
            Response.Flush();
            Response.End();
            gv = null;

            return View(data);
        }
    }
}

Konzole.InventorySystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" content="" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>ETS Customer Service - Springer</title>


    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/metisMenu")
    @Styles.Render("~/Content/timeline")
    @Styles.Render("~/Content/startmin")
    @Styles.Render("~/Content/morris")
    @Styles.Render("~/Content/css/font-awesome.min.css")
    @Styles.Render("~/Content/Site")
    <!-- DataTables CSS -->
    @Styles.Render("~/Content/dataTable-style")
    @Scripts.Render("~/Content/jquery")
    <!-- DataTables JS -->
    @Scripts.Render("~/Content/dataTable-script")
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style type="text/css">
        input:required:focus, select:required:focus {
            border: 1px solid red;
            outline: none;
        }

        input:required:focus, select:required:hover {
            opacity: 1;
        }

        .black-background {
            background-color: #000000;
        }

        .white {
            color: #ffffff;
        }
    </style>
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">ETS Customer Service</a>
            </div>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <ul class="nav navbar-nav navbar-left navbar-top-links">
                <li><a id="btnToggle" href="#" title="Toggle Menu"><i class="fa fa-angle-double-left fa-fw"></i>Menu</a></li>
                <li><a href="#)"><i class="fa fa-home fa-fw"></i> Home</a></li>
            </ul>
            <ul class="nav navbar-right navbar-top-links">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> Setting<b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a href="#" data-toggle="modal" data-target="#mdLogout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- /.navbar-top-links -->
            <div id="dvMenu" class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">

                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-file-text-o fa-fw"></i> Transactions</a>
                        </li>
                        <li>
                            <a href="#" }><i class="fa fa-edit fa-fw"></i> Transaction Logs</a>
                        </li>

                        <li>
                            <a href="#"><i class="fa fa-file-text-o fa-fw"></i> Accounts<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                               <li><a href=@Url.Action("Index", "Suppliers")><i class="fa fa-dashboard fa-fw"></i> Supplier</a></li> 
                                <li><a href=@Url.Action("Index", "Customers")><i class="fa fa-dashboard fa-fw"></i> Customer</a></li>

                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div class="body-banner">
        </div>
        <div class="col-md-12 no-gutter">
            <p class="subheading">
                @ViewBag.Title
                <br clear="both" />
            </p>
        </div>
        <!-- Page Content -->
        @RenderBody()
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->

    <div class="modal fade" id="mdLogout" tabindex="-1" role="dialog" aria-labelledby="mdLogoutLabel" aria-hidden="true">
        <div class="modal-dialog" style="width:350px;top:250px;">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" id="btnCloseLogout" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="mdLogoutLabel">User Log out</h4>
                </div> <!-- /.modal-header -->

                <div class="modal-body">
                    Are you sure you want to log-out?<br />
                    <span style="font-size:9px;">Note: Currect running time will be lost.</span>
                </div> <!-- /.modal-body -->

                <div class="modal-footer">
                    @*@Html.ActionLink("Logout", "LogOff", "Account", routeValues: new { area = "" }, htmlAttributes: new { @class = "btn btn-success", @style = "width:150px;" })*@
                    <button id="btnCancel" class="form-control btn btn-danger" data-dismiss="modal" style="width:150px;">Cancel</button>
                </div> <!-- /.modal-footer -->

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
    @Scripts.Render("~/Content/js")
    @Scripts.Render("~/Content/scripts/custom/layout.js")
    @Scripts.Render("~/Content/scripts/jquery-ui.js")
    @Styles.Render("~/Content/css/jquery-ui.css")
    <script type="text/javascript">
            $("#btnToggle").click(function (e) {

                if ($("#dvMenu").is(':visible')) {
                    $(this).html('<i class="fa fa-angle-double-right fa-fw"></i>Menu');
                    $("#dvMenu").fadeOut();
                    $("#page-wrapper").animate({ "margin-left": '0' });
                }
                else {
                    $(this).html('<i class="fa fa-angle-double-left fa-fw"></i>Menu');
                    $("#page-wrapper").animate({ "margin-left": '250px' });
                    $("#dvMenu").fadeIn();
                }

            });
    </script>
</body>
<footer>

    <div class="footer-div">
        <div id="horizontal-bar-footer"> </div>
    </div>
</footer>
</html>